name: Tests
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan

  test:
    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ckan-version: "ckan-dev:2.11-py3.10"
            ckan-postgres-version: "2.11"
            ckan-solr-version: "2.11-solr9"

    container:
      image: ckan/${{ matrix.ckan-version }}
      options: --user root
    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-solr-version }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
      - uses: actions/checkout@v6
      - name: Install requirements
        run: |
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install -e .
          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
      - name: Setup extension
        run: |
          ckan -c test.ini db init
      - name: Run tests
        run: |
          pytest --ckan-ini=test.ini --cov=ckanext.validation --cov-report=xml --cov-append --disable-warnings -vv -p no:xdist \
            ckanext/validation/tests/test_form.py::TestResourceSchemaForm::test_resource_form_create_json \
            ckanext/validation/tests/test_form.py::TestResourceSchemaForm::test_resource_form_create_upload \
            ckanext/validation/tests/test_form.py::TestResourceSchemaForm::test_resource_form_create_url \
            ckanext/validation/tests/test_form.py::TestResourceSchemaForm::test_resource_form_update \
            ckanext/validation/tests/test_form.py::TestResourceSchemaForm::test_resource_form_update_json \
            ckanext/validation/tests/test_form.py::TestResourceSchemaForm::test_resource_form_update_url \
            ckanext/validation/tests/test_form.py::TestResourceSchemaForm::test_resource_form_update_upload \
            ckanext/validation/tests/test_form.py::TestResourceValidationFieldsPersisted::test_resource_form_fields_are_persisted \
            ckanext/validation/tests/test_interfaces.py::TestInterfaceAsync::test_can_validate_called_on_create_async \
            ckanext/validation/tests/test_interfaces.py::TestInterfaceAsync::test_can_validate_called_on_create_async_no_validation \
            ckanext/validation/tests/test_interfaces.py::TestInterfaceAsync::test_can_validate_called_on_update_async \
            ckanext/validation/tests/test_interfaces.py::TestInterfaceAsync::test_can_validate_called_on_update_async_no_validation \
            ckanext/validation/tests/test_logic.py::TestResourceValidationRun::test_resource_validation_only_called_on_resource_created \
            ckanext/validation/tests/test_logic.py::TestResourceValidationRun::test_resource_validation_only_called_on_resource_updated \
            ckanext/validation/tests/test_logic.py::TestSchemaFields::test_schema_url_field \
            ckanext/validation/tests/test_logic.py::TestSchemaFields::test_schema_upload_field \
            ckanext/validation/tests/test_plugin.py::TestResourceControllerHooksUpdate::test_validation_run_on_upload \
            ckanext/validation/tests/test_plugin.py::TestResourceControllerHooksUpdate::test_validation_run_on_url_change \
            ckanext/validation/tests/test_plugin.py::TestResourceControllerHooksUpdate::test_validation_run_on_schema_change \
            ckanext/validation/tests/test_plugin.py::TestResourceControllerHooksUpdate::test_validation_run_on_format_change \
            ckanext/validation/tests/test_plugin.py::TestResourceControllerHooksCreate::test_validation_run_with_upload \
            ckanext/validation/tests/test_plugin.py::TestResourceControllerHooksCreate::test_validation_run_with_url \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksCreate::test_validation_run_with_upload \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksCreate::test_validation_run_with_url \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksCreate::test_validation_run_only_supported_formats \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksUpdate::test_validation_runs_with_url \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksUpdate::test_validation_runs_with_upload \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksUpdate::test_validation_does_not_run_on_other_formats \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksUpdate::test_validation_run_only_supported_formats \
            ckanext/validation/tests/test_plugin.py::TestPackageControllerHooksUpdate::test_validation_does_not_run_when_config_false

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
